spring:
  application:
    name: manager-service
  redis:
    database: 0
    host: 47.100.183.250
    port: 6379
    password: p@ssw0rd
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 200
        max-wait: 3000ms
  cloud:
    nacos:
      discovery:
        server-addr: nacos.didispace.com:80
      config:
        server-addr: nacos.didispace.com:80
  datasource:
    url: jdbc:mysql://47.100.183.250:3306/DATA_TEST?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001
logging:
  config: classpath:logback-spring.xml
  path: /home/appusr/log
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hjd.net.managerservice.entity
  global-config:
    db-config:
      id-type: auto
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    #    logic-delete-value: 0
    #    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    logic-delete-value: 1
    logic-not-delete-value: 0
    #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
token:
  #  token有效时间，单位分钟 24*60=1440
  tokenExpireTime: 1800
  # 更新令牌时间 2*60=120
  refreshCheckTime: 120
  #  #  RefreshToken过期时间，单位：分钟, 24*60=1440
  #  refreshTokenExpireTime: 1440
  #  shiro缓存有效期，单位分钟,2*60=120
  shiroCacheExpireTime: 120
  #  token加密密钥
  secretKey: bVa7Zr6THLshZIiH

permission-config:
  perms:
    - key: /user/login
      value: anon
    - key: /logout
      value: logout
    - key: /**
      value: jwt